version: "3.9"

services:
  validator-1: &node
    image: anmolnetwork/anmol-node:ibtida

    command:
      - --name=validator-1
      - --chain=/ibtida.json
      - --node-key=0000000000000000000000000000000000000000000000000000000000000001
      - --validator
      - --rpc-cors=all
      - --rpc-external
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --ws-external
      - --unsafe-ws-external
      - --no-prometheus
      - --no-telemetry

    ports:
      - 9933
      - 9944:9944
      - 30333

    networks:
      - ibtida

    volumes:
      - db-validator-1:/data
      - ./chains/raw/ibtida.json:/ibtida.json:ro

    deploy:
      mode: global

    restart: unless-stopped

  validator-2:
    <<: *node
    command:
      - --name=validator-2
      - --chain=/ibtida.json
      - --validator
      - --rpc-cors=all
      - --rpc-external
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --ws-external
      - --unsafe-ws-external
      - --no-prometheus
      - --no-telemetry
      - --bootnodes=/dns4/validator-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

    ports:
      - 9933
      - 9945:9944
      - 30333

    volumes:
      - db-validator-2:/data
      - ./chains/raw/ibtida.json:/ibtida.json:ro

    depends_on:
      - validator-1

volumes:
  db-validator-1:
  db-validator-2:

networks:
  ibtida:
