version: "3.9"

services:
  node-alice: &node
    image: anmolnetwork/anmol-node:latest
    build:
      context: .
      args:
        # Credentials used by sccache
        - SCCACHE_BUCKET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY

    command:
      - --chain=local
      - --rpc-cors=all
      - --rpc-external
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --ws-external
      - --unsafe-ws-external
      - --no-prometheus
      - --alice
      - --node-key=0000000000000000000000000000000000000000000000000000000000000001

    ports:
      - 9933
      - 9944:9944
      - 30333

    volumes:
      - db-alice:/data

    deploy:
      mode: global

    restart: unless-stopped

  node-bob:
    <<: *node
    command:
      - --chain=local
      - --rpc-cors=all
      - --rpc-external
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --ws-external
      - --unsafe-ws-external
      - --no-prometheus
      - --bob
      - --bootnodes=/dns4/node-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

    ports:
      - 9933
      - 9945:9944
      - 30333

    volumes:
      - db-bob:/data

    depends_on:
      - node-alice

volumes:
  db-alice:
  db-bob:
