version: "3.9"

services:
  node-alice: &node
    image: anmolnetwork/anmol-node:ibtida
    build:
      context: .
      args:
        # Credentials used by sccache
        - SCCACHE_BUCKET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY

    command: |
      --chain local
      --ws-external
      --rpc-external
      --no-prometheus
      --alice
      --node-key 0000000000000000000000000000000000000000000000000000000000000001

    ports:
      - 9615
      - 9933
      - 9944
      - 30333

    volumes:
      - db-alice:/var/local/anmol

  node-bob:
    <<: *node
    command: |
      --chain local
      --ws-external
      --rpc-external
      --no-prometheus
      --bob
      --bootnodes /dns4/node-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

    volumes:
      - db-bob:/var/local/anmol

    depends_on:
      - node-alice

volumes:
  db-alice:
  db-bob:
