# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check & Benchmarking

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - 'master'
      - 'ibtida'

  pull_request:
    branches:
      - 'master'
      - 'ibtida'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-20.04

    container:
      image: anmolnetwork/anmol-node-build:latest
      options: --user root -v ${{ github.workspace }}:/build/:rw
      env:
        SCCACHE_BUCKET: ${{ secrets.SCCACHE_BUCKET }}
        SCCACHE_AWS_ACCESS_KEY_ID: ${{ secrets.SCCACHE_AWS_ACCESS_KEY_ID }}
        SCCACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.SCCACHE_AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Lint Code
        run: cargo fmt -- --check

      - name: Check
        run: SKIP_WASM_BUILD=1 cargo check --release

      - name: Test
        run: SKIP_WASM_BUILD=1 cargo test --release

      - name: Check Benchmarks
        run: cargo check --features=runtime-benchmarks --release --manifest-path=node/Cargo.toml
