# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Publish Docker image

on:
  push:
    branches:
      - 'master'
      - 'ibtida'

    tags:
      - 'v*'

  pull_request:
    branches:
      - 'master'
      - 'ibtida'

jobs:
  build-docker-images:
    runs-on: ubuntu-20.04

    outputs:
      image-version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changes on Dockerfile
        id: changed-dockerfile
        uses: tj-actions/changed-files@v1.0.0
        with:
          files: Dockerfile*

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' || github.event_name != 'pull_request' }}

      - name: Login to DockerHub
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' || github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: build-meta
        uses: docker/metadata-action@v3
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' }}
        with:
          images: anmolnetwork/anmol-node-build
          tags: |
            type=ref,event=branch
            type=sha,prefix=,latest=true
          labels: |
            org.opencontainers.image.vendor=Anmol Network
            org.opencontainers.image.url=https://anmol.network

      - name: Build and push builder image
        uses: docker/build-push-action@v2
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' }}
        with:
          file: ./Dockerfile.build
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.build-meta.outputs.tags }}
          labels: ${{ steps.build-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' || github.event_name != 'pull_request' }}
        with:
          images: anmolnetwork/anmol-node
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          labels: |
            org.opencontainers.image.vendor=Anmol Network
            org.opencontainers.image.url=https://anmol.network

      - name: Build and push production image
        uses: docker/build-push-action@v2
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' || github.event_name != 'pull_request' }}
        with:
          build-args: |
            SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }}
            AWS_ACCESS_KEY_ID=${{ secrets.SCCACHE_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.SCCACHE_AWS_SECRET_ACCESS_KEY }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-images:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' }}

    needs:
      - build-docker-images

    steps:
      - name: Update image version of the network spec
        uses: "OnFinality-io/action-onf-release@v1"
        with:
          onf-access-key: ${{ secrets.ONF_ACCESS_KEY }}
          onf-secret-key: ${{ secrets.ONF_SECRET_KEY }}
          onf-workspace-id: ${{ secrets.ONF_WORKSPACE_ID }}
          onf-network-key: ${{ secrets.ONF_NETWORK_KEY }}
          onf-sub-command: image
          onf-action: add
          image-version: ${{ needs.build-docker-images.outputs.image-version }}

      - name: Perform a rolling update to all nodes
        uses: "OnFinality-io/action-onf-release@v1"
        with:
          onf-access-key: ${{ secrets.ONF_ACCESS_KEY }}
          onf-secret-key: ${{ secrets.ONF_SECRET_KEY }}
          onf-workspace-id: ${{ secrets.ONF_WORKSPACE_ID }}
          onf-network-key: ${{ secrets.ONF_NETWORK_KEY }}
          onf-sub-command: node
          onf-action: upgrade
          image-version: ${{ needs.build-docker-images.outputs.image-version }}
          percent: 30
